[package]
name            = "lzr"
version         = "0.1.0"
edition         = "2024"
rust-version    = "1.87"

authors         = ["Chris Reynolds <chris@reynolds.guru>"]
description     = "Fast LZ77-based compression library and CLI."
license         = "MIT OR Apache-2.0"
readme          = "README.md"
repository      = "https://github.com/ckmjreynolds/lzr"
keywords        = ["LZ77", "compression", "compress"]
categories      = ["compression"]
documentation   = "https://docs.rs/lzr"

include         = ["src/**", "Cargo.toml", "README.md", "LICENSE*"]

[dependencies]
# arbitrary-int = "=2.1.1"
# clap = { version = "=4.6.0", features = ["derive"] }
# rayon = "=1.11.0"
# rustc-hash = "=2.1.2"
lipsum = { version = "=0.9.1", optional = true }
static_assertions = "=1.1.0"
# thiserror = "=2.0.18"

[dev-dependencies]
# assert_cmd = "=2.2.0"
criterion = "=0.8.2"
lipsum = "=0.9.1"
pretty_assertions = "=1.4.1"
proptest = "=1.11.0"

[lints.rust]
keyword_idents = { level = "forbid", priority = -1 }
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
non_ascii_idents = "forbid"
rust_2018_idioms = { level = "warn", priority = -1 }
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
unreachable_pub = "deny"
unsafe_code = "forbid"
# Too many false positives in a crate with both a library and executable.
# unused_crate_dependencies = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
redundant_pub_crate = "allow"

[features]
bench-internals = ["lipsum"]

[[bench]]
name = "adler32"
harness = false
required-features = ["bench-internals"]

[[bench]]
name = "entropy"
harness = false
required-features = ["bench-internals"]

[profile.release]
lto = "thin"
codegen-units = 1

[profile.bench]
lto = "thin"
codegen-units = 1
