//! Structural mask for the `moe-tok` codec — Phase 49.
//!
//! At each token boundary the previous source byte is in a state
//! known to both encoder and decoder. This module classifies that
//! byte into 16 categories and stores a per-category bitmask over
//! the BPE vocab marking which token ids ever appeared after a byte
//! of that category in the training corpus. At inference the codec
//! applies a soft penalty to tokens flagged "never seen here," which
//! sharpens the predicted distribution without costing signaling bits.
//!
//! The mask itself is generated by `lzr gen-mask` from a training
//! corpus and embedded in the binary via `include_bytes!`; both
//! encoder and decoder reference the same `MASK`, so the mask is part
//! of `L(D)` (counted at 2× per the Hutter rule) but never signaled.

use std::path::Path;

use anyhow::{Context, Result};

pub(crate) const N_CLASSES: usize = 16;
pub(crate) const VOCAB: usize = 16384;
pub(crate) const BYTES_PER_MASK: usize = VOCAB / 8;
pub(crate) const FILE_BYTES: usize = N_CLASSES * BYTES_PER_MASK;

#[inline]
pub(crate) const fn byte_class(b: u8) -> usize {
    match b {
        b'a'..=b'z' => 0,
        b'A'..=b'Z' => 1,
        b'0'..=b'9' => 2,
        b' ' => 3,
        b'\n' => 4,
        b'\t' | b'\r' => 5,
        b'<' => 6,
        b'>' => 7,
        b'"' => 8,
        b'&' => 9,
        b';' => 10,
        b'=' => 11,
        b'/' => 12,
        b'.' => 13,
        0x21..=0x7E => 14,
        _ => 15,
    }
}

/// One bit per (class, token); 32 KB total. Bit set ⇒ token was
/// observed at least once following a byte in that class in the
/// generator corpus.
#[derive(Debug)]
pub(crate) struct StructMask {
    bits: Vec<u8>,
}

impl StructMask {
    pub(crate) fn zeros() -> Self {
        Self {
            bits: vec![0_u8; FILE_BYTES],
        }
    }

    pub(crate) fn set(&mut self, class: usize, token: u32) {
        let i = (class * BYTES_PER_MASK) + (token as usize / 8);
        self.bits[i] |= 1 << ((token as usize) % 8);
    }

    pub(crate) fn get(&self, class: usize, token: u32) -> bool {
        let i = (class * BYTES_PER_MASK) + (token as usize / 8);
        (self.bits[i] >> ((token as usize) % 8)) & 1 == 1
    }

    pub(crate) fn save(&self, path: &Path) -> Result<()> {
        std::fs::write(path, &self.bits)
            .with_context(|| format!("writing struct mask to {}", path.display()))
    }
}

/// 32 KB structural mask shipped in the binary. Generated by
/// `lzr gen-mask --bpe ckpts/bpe_16k.bin --bytes 100000000 --out
/// assets/struct_mask.bin` from the first 100 MB of `enwik9`.
pub(crate) static MASK: &[u8; FILE_BYTES] = include_bytes!("../assets/struct_mask.bin");

#[inline]
pub(crate) fn mask_bit(class: usize, token: u32) -> bool {
    let i = (class * BYTES_PER_MASK) + (token as usize / 8);
    (MASK[i] >> ((token as usize) % 8)) & 1 == 1
}
